version: '3.2'
services:
  psstore:
    image: psstore:local
    build:
      context: '../../'
      dockerfile: 'examples/simple-counter/counter-store/Dockerfile'
  server:
    build:
      context: '../../'
      dockerfile: 'examples/simple-counter/server/Dockerfile'
    command: ['npm', 'start']
    ports:
      - 7001:7001
    depends_on:
      - psstore
  client:
    build:
      context: '../../'
      dockerfile: 'examples/simple-counter/client/Dockerfile'
#    command: ['nginx', '-g', 'daemon off;']
    command: ['npm', 'start']
    depends_on:
      - psstore
      - server
    volumes:
      - ./client/src:/usr/app/src
    environment:
      - WS_ENDPOINT=ws://localhost:7001
    ports:
      - 7000:1234
